import os

import fitz  # PyMuPDF

from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas


# ============================================
# Extract Text From Uploaded PDF
# ============================================

def extract_text_from_pdf(pdf_path: str):

    document = fitz.open(pdf_path)

    text = ""

    for page in document:

        text += page.get_text()

    document.close()

    return text


# ============================================
# Generate Health Report PDF
# ============================================

def generate_health_report_pdf(report, analysis):

    folder = "generated_reports"

    os.makedirs(
        folder,
        exist_ok=True
    )

    file_path = os.path.join(
        folder,
        f"MediMind_Report_{report.id}.pdf"
    )

    pdf = canvas.Canvas(
        file_path,
        pagesize=letter
    )

    width, height = letter

    y = height - 50

    pdf.setFont(
        "Helvetica-Bold",
        20
    )

    pdf.drawString(
        50,
        y,
        "MediMind AI Health Report"
    )

    y -= 50

    pdf.setFont(
        "Helvetica",
        12
    )

    pdf.drawString(
        50,
        y,
        f"Report Name: {report.file_name}"
    )

    y -= 25

    

    pdf.drawString(
        50,
        y,
        f"Uploaded At: {report.created_at}"
    )

    y -= 40

    pdf.setFont(
        "Helvetica-Bold",
        14
    )

    pdf.drawString(
        50,
        y,
        f"Health Score: {analysis.health_score}/100"
    )

    y -= 40

    pdf.setFont(
        "Helvetica-Bold",
        14
    )

    pdf.drawString(
        50,
        y,
        "Blood Values"
    )

    y -= 25

    pdf.setFont(
        "Helvetica",
        12
    )

    for key, value in analysis.blood_values.items():

        pdf.drawString(
            70,
            y,
            f"{key}: {value}"
        )

        y -= 20

    y -= 20

    pdf.setFont(
        "Helvetica-Bold",
        14
    )

    pdf.drawString(
        50,
        y,
        "AI Analysis"
    )

    y -= 25

    pdf.setFont(
        "Helvetica",
        12
    )

    for key, value in analysis.analysis_result.items():

        pdf.drawString(
            70,
            y,
            f"{key}: {value}"
        )

        y -= 20

    y -= 30

    pdf.setFont(
        "Helvetica-Oblique",
        10
    )

    pdf.drawString(
        50,
        y,
        "Generated by MediMind AI"
    )

    pdf.save()

    return file_path